# Generated by Django 4.2.6 on 2023-11-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_shortenurl_click_count_shortenurl_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenurl',
            name='short_key',
        ),
        migrations.AddField(
            model_name='shortenurl',
            name='short_url',
            field=models.URLField(null=True),
        ),
    ]
